name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: "documentation-${{ github.ref }}"
  cancel-in-progress: true

env:
  BUNDLE_WITH: maintenance

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v7

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ruby
        bundler-cache: true
    
    - name: Installing packages
      run: sudo apt-get install wget
    
    - name: Generate documentation
      timeout-minutes: 5
      run: bundle exec bake utopia:project:static --force no
    
    - name: Upload documentation artifact
      uses: actions/upload-pages-artifact@v5
      with:
        path: docs
  
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write
    
    environment:
      name: ${{ github.event_name == 'pull_request' && 'github-pages-preview' || 'github-pages' }}
      url: ${{steps.deployment.outputs.page_url}}
    
    needs: generate
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
        with:
          preview: ${{ github.event_name == 'pull_request' }}
